### ISSUE TITLE
Add loader when image is loading

### ISSUE THREAD

**Issue by TheShiveshNetwork** [TheShiveshNetwork/Pokedex#1]
## What does this issue mean?
On page load, the images take some time while loading. The fix must add a loader or may be a skeleton that matches the app theme to display while the image is loading.

## Steps to fix the issue
- Create a custom loader / skeleton
- Define a hook to check if image is loading
- If the image is loading, then display the loader or skeleton

## How to contribute
If you are interested, reply below and I'll assign this to you.
- Create a PR
- Submit and wait for response
- If the PR is reviewed, it wil be merged

### Happy Hacking !!!

**Comment by Thanush19** [comment]
i'll fix this

**Comment by theavitw** [comment]
@TheShiveshNetwork 
I can do this

**Comment by TheShiveshNetwork** [comment]
@Thanush19 @theavitw assigned! Work on it fast.

**Comment by Thanush19** [comment]
@TheShiveshNetwork kindly review the PR #5
