### ISSUE TITLE
Improve the pokemon card UI

### ISSUE THREAD

**Issue by TheShiveshNetwork** [TheShiveshNetwork/Pokedex#10]
## What does this issue mean?
The pokemon cards need Improvement in style.

## Steps to fix the issue
- A better style will be considered

## How to contribute
If you are interested, reply below and I'll assign this to you.
- Create a PR
- Submit and wait for response
- If the PR is reviewed, it wil be merged

### Happy Hacking !!!

**Comment by CodeStrate** [comment]
@TheShiveshNetwork brother can I be assigned to this issue?

**Comment by TheShiveshNetwork** [comment]
@CodeStrate go ahead!
