### ISSUE TITLE
Add infinite scrolling on homepage

### ISSUE THREAD

**Issue by dev-palwar** [TheShiveshNetwork/Pokedex#11]
## Context
On the homepage, there are only 20 Pokemon cards.

## Expected behavior
The API should fetch and display more data as we scroll

**Comment by TheShiveshNetwork** [comment]
Hi, @dev-palwar this issue is already open. Check out #7

**Comment by dev-palwar** [comment]
Oh sorry i didn't see that.

**Comment by dev-palwar** [comment]
Btw I've made some enhancements regarding it. Would you look to see it?
