### ISSUE TITLE
add dark mode (my eyes hurt)

### ISSUE THREAD

**Issue by lstuma** [TheShiveshNetwork/Pokedex#12]

**Comment by TheShiveshNetwork** [comment]
@lstuma are you working on it?

**Comment by lstuma** [comment]
would love to but i don't know when i'll have the time to actually do it, so it might take a while

**Comment by TheShiveshNetwork** [comment]
Alright, this issue will be open. If we don't get any contributor then you can work on that!

**Comment by bhavik001** [comment]
Hello @TheShiveshNetwork !
Can you please assign me to work on this issue and can you please label this as a hactoberfest.

Please reply!
Thank you!

**Comment by TheShiveshNetwork** [comment]
@bhavik001 are you still interested? But, Hacktoberfest is already over. Although I'm going to assign this to you!

**Comment by Namatuzio** [comment]
@TheShiveshNetwork Hey again! Could you also assign this to me?
