### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by Namatuzio** [TheShiveshNetwork/Pokedex#15]
I thought of some new additions to the search feature. I think it would be really neat if users would be able to "filter" based on various conditions. My first thought is by generation, i.e. a user can look at only gen 5 pokemon or maybe only gen 2 pokemon. I'll definitely look into what other possibilities could be done with filtering but as for now, this is the base functionality for advanced search I want to add. 

Let me know what you think @TheShiveshNetwork and please assign me to this issue if you approve. Thanks!

**Comment by TheShiveshNetwork** [comment]
@Namatuzio go ahead!
