### ISSUE TITLE
Height and Weight for each pokemon are incorrect units

### ISSUE THREAD

**Issue by terrylh22** [TheShiveshNetwork/Pokedex#20]
The API documentation shows that the height number returned is in decimeters and the weight is in hectograms. Not sure which metric you would prefer to show but may need a calculation to convert those numbers to m and kg if you would like to use those still.

(I'm new to open source but saw this and figured I would open an issue. Let me know if I did this wrong!)

**Comment by TheShiveshNetwork** [comment]
I'd prefer meters and kgs.
And yeah, you did this correct.
I'll assign this to you  and you can start working on this.
Happy Hacking!!
