### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by Namatuzio** [TheShiveshNetwork/Pokedex#22]
Hey again @TheShiveshNetwork, I would like to add custom themes to the site, if you want I could also package the dark mode stuff into there!

**Comment by TheShiveshNetwork** [comment]
Great @Namatuzio , Go ahead !!

**Comment by Namatuzio** [comment]
Hi @TheShiveshNetwork could you reopen this? I had some additional themes in mind that would make use of the other sprites that are available through the API. Thanks!
