### ISSUE TITLE
Add infinite scroll to the app

### ISSUE THREAD

**Issue by TheShiveshNetwork** [TheShiveshNetwork/Pokedex#7]
## What does this issue mean?
The page currently has only a few number of Pokemons. Add an infinite scroll so that when user scrolls down the page, knew pokemons starting showing up.

## Steps to fix the issue
- Use the pokeapi (firstly it fetches 25 pokemons, after scroll it should fetch 50)
- When user scrolls down the page, fetch the further pokemon data
- Render the new fetched data

Any better approach can also be considered.

## How to contribute
If you are interested, reply below and I'll assign this to you.
- Create a PR
- Submit and wait for response
- If the PR is reviewed, it wil be merged

### Happy Hacking !!!

**Comment by terrylh22** [comment]
Hey, could you add a license to the project please? Thank you!

**Comment by TheShiveshNetwork** [comment]
@terrylh22 Yupp, done!

**Comment by darshitdudhaiya** [comment]
@TheShiveshNetwork  i would like to contribute into so can you assign it to me

**Comment by TheShiveshNetwork** [comment]
@darshitdudhaiya assigned!
Happy hacking!

**Comment by darshitdudhaiya** [comment]
@TheShiveshNetwork  thank you to assign it to me i give my best in to it

**Comment by darshitdudhaiya** [comment]
@TheShiveshNetwork i just commited so can you check it out and if there is any changes are there so pls inform me for it.
