### ISSUE TITLE
Improve the pokemon search

### ISSUE THREAD

**Issue by TheShiveshNetwork** [TheShiveshNetwork/Pokedex#9]
## What does this issue mean?
Currently the search works on only the rendered pokemon cards. It should search in the whole pokemon response.

## Steps to fix the issue
- Use the pokeapi to get all the pokemons and filter for the searched keyword in pokemon name
- Display the filtered pokemon cards
- Optimize the code. It should not have multiple api calls that slow down the app.

## How to contribute
If you are interested, reply below and I'll assign this to you.
- Create a PR
- Submit and wait for response
- If the PR is reviewed, it wil be merged

### Happy Hacking !!!

**Comment by Namatuzio** [comment]
Hi, I'd like to work on this.

**Comment by TheShiveshNetwork** [comment]
@Namatuzio go ahead!
